# Generated by Django 6.0.4 on 2026-05-14 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='mobilenumber',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
