# Generated by Django 6.0.4 on 2026-05-14 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application1', '0002_login_mobilenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='mobilenumber',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
