# Generated by Django 6.0.4 on 2026-05-19 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application1', '0003_alter_login_mobilenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='mobilenumber',
            field=models.CharField(max_length=15),
        ),
    ]
