# Generated by Django 6.0.4 on 2026-05-19 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application1', '0004_alter_login_mobilenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=20)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('area_no', models.IntegerField()),
                ('charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('arrival_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Parked', 'Parked'), ('Leaved', 'Leaved')], default='Parked', max_length=10)),
            ],
        ),
    ]
