# Generated by Django 6.0.4 on 2026-05-20 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application1', '0005_vehicleentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleentry',
            name='action',
            field=models.CharField(choices=[('Parked', 'Parked'), ('Leaved', 'Leaved')], default='Register', max_length=10),
        ),
    ]
