# Generated by Django 6.0.4 on 2026-05-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application1', '0007_alter_vehicleentry_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleentry',
            name='action',
            field=models.CharField(choices=[('register', 'Register'), ('NotRegistger', 'NotRegister')], default='register', max_length=20),
        ),
    ]
