# Generated by Django 6.0.4 on 2026-05-22 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application1', '0009_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleentry',
            name='action',
            field=models.CharField(choices=[('register', 'Register'), ('NotRegister', 'NotRegister')], default='register', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicleentry',
            name='area_no',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicleentry',
            name='vehicle_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application1.category'),
        ),
    ]
