# Generated by Django 6.0.4 on 2026-06-03 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application1', '0010_alter_vehicleentry_action_alter_vehicleentry_area_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleentry',
            name='action',
            field=models.CharField(choices=[('Parked', 'Parked'), ('Leaved', 'Leaved')], default='register', max_length=20),
        ),
    ]
