# Generated by Django 6.0.4 on 2026-06-03 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application1', '0011_alter_vehicleentry_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('car_type', models.CharField(blank=True, max_length=100)),
                ('tyres', models.IntegerField(blank=True, null=True)),
                ('area_number', models.CharField(max_length=100)),
                ('parking_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
