# Generated by Django 6.0.4 on 2026-06-03 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application1', '0012_subcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='category',
            new_name='vehicle_type',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='car_type',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='tyres',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='wheels',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
    ]
