# Generated by Django 6.0.4 on 2026-06-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application1', '0013_rename_category_subcategory_vehicle_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='wheels',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='category',
            field=models.CharField(default='car', max_length=100),
            preserve_default=False,
        ),
    ]
