# Generated by Django 6.0.4 on 2026-06-03 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application1', '0014_remove_subcategory_wheels_subcategory_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
